version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sharingDB
    ports:
      - "3000:5432"
    networks:
      - social-media
    volumes:
      - shared-volume:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    networks:
      - social-media
    volumes:
      - shared-volume:/localstack/data

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started
    networks:
      - social-media
    volumes:
      - shared-volume:/app/data

networks:
  social-media:
    driver: bridge

volumes:
  shared-volume:
